// Code generated by hertz generator.

package example

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _hellomethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _newmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _othermethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _othermethod0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _studentmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _studentothermethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _studentaddmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}
