// Code generated by hertz generator.

package example

import (
	"context"
	example "github.com/T-THA/thrift-test/biz/model/hello/example"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

var Smap = make(map[int32]example.AddReq)

// StudentMethod .
// @router /query [GET]
func StudentMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req example.StudentReq

	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	if retMes, b := Smap[req.Id]; b {
		c.JSON(consts.StatusOK, utils.H{
			"Id":       retMes.Id,
			"Name":     retMes.Name,
			"Favorite": retMes.Favorite,
		})
	} else {
		c.JSON(consts.StatusNotFound, utils.H{"message": "No such student"})
	}
}

// StudentAddMethod .
// @router /add [POST]
func StudentAddMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req example.AddReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	Smap[req.Id] =req

	resp := new(example.AddResp)
	resp.RespBody = "success"

	c.JSON(consts.StatusOK, resp)
}
